package it.prova.biblioteca.model;

public enum Genere {
	FANTASCIENZA, FANTASY, HORROR, GIALLO, THRILLER, ROMANZO_STORICO, ROMANZO_ROSA, NARRATIVA_CONTEMPORANEA, SAGGISTICA,
	BIOGRAFIA, AUTOBIOGRAFIA, MEMORIE, POESIA, DRAMMA, AVVENTURA, FANTAPOLITICA, WESTERN, UMORISMO, EPISTOLARE,
	MITOLOGIA
}
